# Board-esp32dev-Arduino.yaml
esphome:
  on_boot:
    priority: -200  # Executes after base.yaml's -100 priority
    then:
      - lambda: |-
          esp_reset_reason_t reason = esp_reset_reason();
          if (reason == ESP_RST_DEEPSLEEP) {
            std::string pin_str = "${wakeup_pin}";
            int wakeup_pin_num;
            if (pin_str.rfind("GPIO", 0) == 0) {  // Check if starts with "GPIO"
              wakeup_pin_num = atoi(pin_str.c_str() + 4);  // Skip "GPIO" and parse number
            } else {
              wakeup_pin_num = atoi(pin_str.c_str());  // Plain number
            }
            gpio_num_t pin = static_cast<gpio_num_t>(wakeup_pin_num);
            ESP_LOGI("wakeup", "[BOOT] GPIO%d state at wakeup: %d", wakeup_pin_num, gpio_get_level(pin));
          }
      - delay: 30s      # Wait for PMS7003 warmup before sending active mode command

esp32:
  board: esp32dev  #devkit v1
  framework:
    type: esp-idf
    
substitutions:
  wakeup_pin: GPIO34  # 
  wakeup_pin_mode: INVERT_WAKEUP
#  usb_detect_pin: GPIO #          ADC1_CH5, safe/D3 - was 9/USB power (e.g., high if powered)/wired to VBUS for battery monitor
#  stay_awake_pin: GPIO #                 D10/MOSI/Status LED/SPI
#  #battery_adc_pin: GPIO #ADC1_CH3, safe/A1/D1/ADC1_CH3. Ideal for battery voltage (analog read with divider for 3.7V LiPo)
  i2c_sda_pin: GPIO21 #I2C SDA
  i2c_scl_pin: GPIO22 #I2C SCL
#  status_led: GPIO #                    Safe for status LED/D10/MOSI/deepsleep wake
#  safe_boot_pin: GPIO0 #OK (input/output) no pin
  pms_rx_pin: GPIO16
  pms_tx_pin: GPIO17
  pms_reset_pin: GPIO26  # hardware reset
  pms_enable_pin: GPIO27  # SET/enable control (e.g., active/passive mode)
  spi_clk_pin: GPIO18   # Display Clock ili9xxx, model: st7735
  spi_mosi_pin: GPIO23  # Display Data Out ili9xxx, model: st7735
  spi_cs_pin: GPIO5     # Display Chip Select ili9xxx, model: st7735
  lcd_dc_pin: GPIO4     
  display_prox_trig: GPIO35           # Display Poximity Trigger ili9xxx, model: st7735
  display_backlight_output: GPIO15    # backlight_output on/off 0-100%
  gas_heater_switch: GPIO13           # Gas Sensor Heater Control
  mic_i2s_lrclk_pin: GPIO14     # Mic SPH0645LM4H Word Select / Frame Sync (WS/LRCLK)
  mic_i2s_bclk_pin: GPIO25      # Mic SPH0645LM4H Bit Clock (BCLK)
  mic_i2s_din_pin: GPIO12       # Mic SPH0645LM4H Data In (DOUT/DIN)
  
i2c:  
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  scan: true
  id: bus_a

#uart:
#  - id: ${pms_uart_id}
#    rx_pin: ${pms_rx_pin}
#    tx_pin: ${pms_tx_pin}
#    baud_rate: ${pms_baud_rate}
#    rx_buffer_size: 512 # test 
    
#  - id: ${mh_uart_id}
#    rx_pin: ${mh_rx_pin}
#    tx_pin: ${mh_tx_pin}
#    baud_rate: ${mh_baud_rate}
#    rx_buffer_size: 512 # test 