#Board-Teyleten-Robot-D1-Mini-ESP32-Arduino-NodeMCU.yaml
# https://github.com/nkitanov/iaq_board/blob/master/firmware/iaq_board.yaml
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    
substitutions:
  wakeup_pin: GPIO4  #Need to identify 
  wakeup_pin_mode: INVERT_WAKEUP
  usb_detect_pin: GPIO35 #          ADC1_CH5, safe/D3 - was 9/USB power (e.g., high if powered)/wired to VBUS for battery monitor
  stay_awake_pin: GPIO5 #                 D10/MOSI/Status LED/SPI
  #battery_adc_pin: GPIO3 #ADC1_CH3, safe/A1/D1/ADC1_CH3. Ideal for battery voltage (analog read with divider for 3.7V LiPo)
  i2c_sda_pin: GPIO21 #I2C SDA
  i2c_scl_pin: GPIO22 #I2C SCL
  status_led: GPIO2 #                    Safe for status LED/D10/MOSI/deepsleep wake
  safe_boot_pin: GPIO0 #OK (input/output) no pin
  #pwm_output: GPIO3 #ADC1_CH3, safe/A1/D1/deepsleep wake
  
  #tx_pin: GPIO19 #tx_pin for CO2/ miso_pin?
  mosi_pin: GPIO23 #
  pms_rx_pin: GPIO18
  pms_tx_pin: GPIO19
  pms_baud_rate: 9600
  # UART for MH (e.g., MH-Z19)
  mh_uart_id: mh
  mh_rx_pin: GPIO16  # May conflict with USB serial; remap if needed (e.g., to GPIO16)
  mh_tx_pin: GPIO17  # May conflict; remap if needed (e.g., to GPIO17)
  mh_baud_rate: 9600
  # PMSX003 sensor settings
  pms_update_interval: 120s
  pms_pm10_name: "${device_name} PM10.0"
  pms_pm2_5_name: "${device_name} PM2.5"
  pms_pm1_name: "${device_name} PM1.0"
  pms_uart_id: pms
  
i2c:  # Add this section
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  scan: true
  id: bus_a

#Physically connect PMS7003 RX to GPIO19 (board TX). 
#GPIO19 is safe on ESP32 D1 Mini (it's UART2_TX by default, no conflicts with USB serial or flash).  
uart:
  - id: ${pms_uart_id}
    rx_pin: ${pms_rx_pin}
    tx_pin: ${pms_tx_pin}
    baud_rate: ${pms_baud_rate}
    
    #MH UART (Commented Out): If you're planning to enable the MH-Z19 (CO2 sensor), note that GPIO1 (RX)
    #and GPIO3 (TX) are the default USB serial pins on ESP32. This can conflict with logging or OTA. 
    #Remap to free pins like GPIO16 (RX) and GPIO17 (TX) via substitutions
  - id: ${mh_uart_id}
    rx_pin: ${mh_rx_pin}
    tx_pin: ${mh_tx_pin}
    baud_rate: ${mh_baud_rate}
    
