#AITrip ESP32-C3 FN4 SUPER MINI
substitutions:
  # GPIO8 - internal LED
  # GPIO9 - boot button
  # GPIO2 - strapping/boot mode
  
  wakeup_pin: GPIO1  #ADC1_CH1 (safe ADC)/deep sleep wake (low trigger), ADC1_CH1 for analog. Safe for boot (no strapping issue). Good choice for wake.
  wakeup_pin_mode: INVERT_WAKEUP
  usb_detect_pin: GPIO7 #SS/digital I/O, often CS/SS for SPI. Safe for input to detect USB power (e.g., high on VBUS).
  stay_awake_pin: GPIO2 #A2/ADC1_CH2, digital I/O. Safe, no boot conflicts
  # battery_adc_pin: GPIO4 #ADC1_CH4 (safe ADC)/SCK/A4/ADC1_CH4, digital I/O, SCK for SPI. Excellent for battery voltage (analog read).
  i2c_sda_pin: GPIO8 #I2C SDA /digital I/O. Strapping pin—pull-up on boot ok for I2C.
  i2c_scl_pin: GPIO9 #I2C SCL /digital I/O. Strapping pin—similar to GPIO8.
  status_led: GPIO10 #OK (status LED, PWM, etc.)/digital I/O, PWM-capable. Often used for LED on C3 minis (external if no built-in). Safe.
  safe_boot_pin: GPIO0 #OK (input/output)/digital I/O, strapping (boot button). Safe for input/output after boot.
  # pwm_output: GPIO3 #ADC1_CH3 (safe ADC)/A3/ADC1_CH3, PWM-capable. Good for output/analog.
  pms_rx_pin: GPIO20 #RX/UART0_RX default. Fixed for serial.
  pms_tx_pin: GPIO21 #TX/UART0_TX default. Fixed for serial.
  miso_pin: GPIO5 #A5/MISO/ADC1_CH5, MISO for SPI.
  mosi_pin: GPIO6 #MOSI/digital I/O, MOSI for SPI.
  #voltage divider on battery_adc_pin (to handle LiPo 4.2V). If using external LED on status_led, add resistor. For USB detect, wire to VBUS (5V) with divider to 3.3V.
  pms_baud_rate: 9600
  # UART for MH (e.g., MH-Z19) Test for stability, as UART1 on C3 has some limitations (e.g., no hardware flow control). If logs show issues (e.g., no data), swap RX/TX wiring or try lower baud rates initially.
  mh_uart_id: mh
  mh_rx_pin: GPIO4  # or 10 / 5 - safe for RX, PWM-capable but no default conflicts
  mh_tx_pin: GPIO3  # or 1 safe for TX, also ADC1_CH1 but fine for UART
  mh_baud_rate: 9600
  # PMSX003 sensor settings
  pms_update_interval: 120s
  pms_pm10_name: "${device_name} PM10.0"
  pms_pm2_5_name: "${device_name} PM2.5"
  pms_pm1_name: "${device_name} PM1.0"
  pms_uart_id: pms
  esp32_board: esp32-c3-devkitm-1
  esp_framework_type: esp-idf

esp32:
  board: ${esp32_board}
  framework:
    type: ${esp_framework_type}

i2c:  # Add this section
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  scan: true
  id: bus_a

#Physically connect PMS7003 RX to GPIO19 (board TX). 
#GPIO19 is safe on ESP32 D1 Mini (it's UART2_TX by default, no conflicts with USB serial or flash).  
uart:
  - id: ${pms_uart_id}
    rx_pin: ${pms_rx_pin}
    tx_pin: ${pms_tx_pin}
    baud_rate: ${pms_baud_rate}
    
    #MH UART (Commented Out): If you're planning to enable the MH-Z19 (CO2 sensor), note that GPIO1 (RX)
    #and GPIO3 (TX) are the default USB serial pins on ESP32. This can conflict with logging or OTA. 
    #Remap to free pins like GPIO16 (RX) and GPIO17 (TX) via substitutions
  - id: ${mh_uart_id}
    rx_pin: ${mh_rx_pin}
    tx_pin: ${mh_tx_pin}
    baud_rate: ${mh_baud_rate}

  