substitutions:   # main-seeed-xiao-esp32-c3.yaml
  device_name: xiaoc32-2 
  friendly_name: XIAO32-C3 2 (url) #
  api_key: ""  # Disables API encryption for testing  
  ota_password: ""  # Secure OTA password 
  ap_password: ""
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_power_save_mode: LIGHT # NONE, LIGHT, MODEM
  wifi_use_address: 192.168.158.xxx
  manual_ip_static_ip: 192.168.158.xxx
  manual_ip_gateway: 192.168.158.1
  manual_ip_subnet: 255.255.255.0
  ap_ssid: "XIAO Fallback"
  ap_password: "12345678"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

# Enable logging
logger:
  level: VERY_VERBOSE #DEBUG  # Set to highest to enable all runtime select options; lower if you want to restrict
  baud_rate: 115200  # Keep for debugging; set to 0 once stable to disable serial logs
  

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key} 

ota:
  - platform: esphome
    password: ${ota_password} 

wifi:
  power_save_mode: ${wifi_power_save_mode} 
  use_address: ${wifi_use_address}
  output_power: 8.5  # Lower TX power to save battery

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${ap_ssid} 
    password: ${ap_password} 

  # Fallback to AP if WiFi connection fails
  manual_ip:  # Optional for fixed IP after setup
    static_ip: ${manual_ip_static_ip}
    gateway: ${manual_ip_gateway}
    subnet: ${manual_ip_subnet}

captive_portal:

mdns:
  disabled: false

web_server:
  port: 80
  include_internal: true        

# Modular Packages
packages:
  max17048: !include iaq-project/packages/max17048.yaml #max17048 Fuel Guage
  aht20: !include iaq-project/packages/aht20.yaml #temp/hum sensor
  pmsx003: !include  iaq-project/packages/PMSX003.yaml #PMSX003, 7003
  board: !include iaq-project/boards/Board-Seeed-Xiao-ESP32-C3.yaml #Board specific GPIO, etc.
  base: !include iaq-project/common/base.yaml  # Hardware, logger, wifi, api, ota, etc.
  sensors: !include iaq-project/common/sensors.yaml  # All sensors and text_sensors
  sleep: !include iaq-project/common/sleep.yaml  # Deep sleep, globals, intervals
  diagnostics: !include iaq-project/common/diagnostics.yaml # resets, reasons
