substitutions:   # Main-Seeed-Xiao-ESP32-C3.yaml
  device_name: xiaoc3-1
  friendly_name: XIAO32-C3 1 (180)
  api_key: "fmlpfRzTy+RXkwsNjjdKiGJDPWFKRWsqwDxk4fyAEBI="  # Disables API encryption for testing
  ota_password: "dba6cbb118b753240121b7d266f9ff56"  # Secure OTA password
#  #wifi_ssid: !secret wifi_ssid
#  #wifi_password: !secret wifi_password
  wifi_power_save_mode: LIGHT # NONE, LIGHT, MODEM
  wifi_use_address: 192.168.158.180
  manual_ip_static_ip: 192.168.158.180
  manual_ip_gateway: 192.168.158.1
  manual_ip_subnet: 255.255.255.0
  ap_ssid: "XIAO Fallback" #
  ap_password: "12345678" #
  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

logger:
  level: VERY_VERBOSE  # Set to highest to enable all runtime select options; lower if you want to restrict
  baud_rate: 0 # 115200  # Keep for debugging; set to 0 once stable to disable serial logs

wifi:
  power_save_mode: ${wifi_power_save_mode}
  use_address: ${wifi_use_address}
  ap:
    ssid: ${ap_ssid}
    password: ${ap_password}

  # Fallback to AP if WiFi connection fails
  manual_ip:  # Optional for fixed IP after setup
    static_ip: ${manual_ip_static_ip}
    gateway: ${manual_ip_gateway}
    subnet: ${manual_ip_subnet}

api:
  encryption: 
    key: ${api_key}

ota:
  - platform: esphome
    password: ${ota_password}

captive_portal:

mdns:
  disabled: false

web_server:
  port: 80
  include_internal: true      

#  # - !include iaq-project/packages/aht20.yaml #temp/hum sensor (commented out in original)
packages:
  - !include iaq-project/packages/aht20bmp280.yaml #AHT20-BMP280 t/h/pres
  - !include iaq-project/packages/sgp30.yaml # eCO2, TVOC, 
  - !include iaq-project/packages/MH-Z19.yaml #mh-z19 CO2 Sensor
  - !include iaq-project/packages/max17048.yaml #max17048 Fuel Guage
  - !include iaq-project/packages/PMSX003.yaml #PMSX003, 7003
  - !include iaq-project/boards/Board-Seeed-Xiao-ESP32-C3.yaml #Board specific GPIO, etc.
  - !include iaq-project/common/base.yaml  # Hardware, logger, wifi, api, ota, etc.
  - !include iaq-project/common/sensors.yaml  # All sensors and text_sensors
  - !include iaq-project/common/sleep.yaml  # Deep sleep, globals, intervals
  - !include iaq-project/common/diagnostics.yaml # resets, reasons