substitutions:   # Main-Seeed-Xiao-ESP32-C3.yaml
  device_name: "espdolce1"
  friendly_name: espdolce1 (171)
  api_key: "vOQUzPCFGFa70g/jVtF4G/nS3blK1FLvjmqyHr5WFUg="  #"EmrlF+oSzREdx9za2vkvF7igU3WeQpVfsDuw9aNf/4E="  # Disables API encryption for testing
  ota_password: "9c5522bc4cf7bf00b10538634c0d8bf3"   #"41def07295f8022fbb33225b9baa335a"  # Secure OTA password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_power_save_mode: LIGHT # NONE, LIGHT, MODEM
  wifi_use_address: 192.168.119.171  #
  manual_ip_static_ip:  # 192.168.119.171
  manual_ip_gateway:  #  192.168.119.1
  manual_ip_subnet:  #  255.255.255.0
  ap_ssid: "Espdolce1 Fallback Hotspot"  #"Xiao32-C3-3-004 Fallback Hotspot" #
  ap_password: "O0nyVZTC5Hbo"  #"cDz18PDbhSop" #
  espnow_id: esp32_2_151  # No hyphens or spaces; valid C++ identifier
  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

#esp32:
#  board: nodemcu-32s
#  framework:
#    type: esp-idf  # arduino  

#debug:
#  update_interval: 30s

logger:
  level: VERY_VERBOSE  # Set to highest to enable all runtime select options; lower if you want to restrict
  baud_rate: 0 # 115200  # Keep for debugging; set to 0 once stable to disable serial logs

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: ${wifi_power_save_mode}
  use_address: ${wifi_use_address}
  ap:
    ssid: ${ap_ssid}
    password: ${ap_password}

  # Fallback to AP if WiFi connection fails
#  manual_ip:  # Optional for fixed IP after setup
#    static_ip: ${manual_ip_static_ip}
#    gateway: ${manual_ip_gateway}
#    subnet: ${manual_ip_subnet}

api:
  encryption: 
    key: ${api_key}

ota:
  - platform: esphome
    password: ${ota_password}

captive_portal:

mdns:
  disabled: false

web_server:
  port: 80
  include_internal: true  

# i2c:

# bme680_bsec:

packages:
#  - !include iaq-project/packages/bmp280_espnow_pressure_publish.yaml # espnow broadcast pressure sensor
#  - !include iaq-project/packages/bmp280_espnow_weathertrend_publish.yaml # espnow broadcast calc'd weather trend
  - !include iaq-project/common/espnow.yaml # shared sensor broadcast
#  - !include iaq-project/packages/aht20bmp280.yaml #AHT20-BMP280 t/h/pres
#  - !include iaq-project/packages/aht20.yaml # temp/hum sensor
##   - !include iaq-project/packages/BME680_688.yaml # temp/hum/pres/ sensor
#  - !include iaq-project/packages/sgp30.yaml # eCO2, TVOC, 
#  - !include iaq-project/packages/MH-Z19.yaml #mh-z19 CO2 Sensor
#  - !include iaq-project/packages/SSD1306-64x48.yaml  # display2
#  - !include iaq-project/packages/SSD1306-128x64-local.yaml  # display1 local with bmp280 sensor
#  - !include iaq-project/packages/SSD1306-128x64-local-w-countdown.yaml  # with countdown to sleep. display1/2, local (with bmp280 sensor) or remote    
#  - !include iaq-project/packages/display-fonts.yaml  # arial
#  - !include iaq-project/packages/max17048.yaml #max17048 Fuel Guage
#  - !include iaq-project/packages/PMSX003.yaml #PMSX003, 7003
  - !include iaq-project/boards/Board-esp32-nodemcu-32s-Arduino.yaml #Board specific GPIO, etc.
  - !include iaq-project/common/base.yaml  # Hardware, logger, wifi, api, ota, etc.
  - !include iaq-project/common/sensors.yaml  # All sensors and text_sensors
  - !include iaq-project/common/sleep.yaml  # Deep sleep, globals, intervals
  - !include iaq-project/common/diagnostics.yaml # resets, reasons
  - !include iaq-project/common/esphome_includes.yaml # componnts