substitutions:   # Main-AITrip-ESP32-C3-FN4-Super-Mini.yaml
  device_name: supermini-2
  friendly_name: Super Mini32 2 (100)
  # api_key: #"fmlpfRzTy+RXkwsNjjdKiGJDPWFKRWsqwDxk4fyAEBI="  # Commented out: Disables API encryption for testing per your request.
  ota_password: "test"
  #wifi_ssid: !secret wifi_ssid
  #wifi_password: !secret wifi_password
  wifi_power_save_mode: LIGHT # NONE, LIGHT, MODEM
  wifi_use_address: 192.168.158.100
  manual_ip_static_ip: 192.168.158.100
  manual_ip_gateway: 192.168.158.1
  manual_ip_subnet: 255.255.255.0
  ap_ssid: "Mini Fallback"
  ap_password: "12345678"
  espnow_id: supermini_2  # No hyphens or spaces; valid C++ identifier

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

#debug:
#  update_interval: 30s

logger:
  level: VERY_VERBOSE
  baud_rate: 0   # 115200 #0

wifi:
  use_address: ${wifi_use_address}
  power_save_mode: ${wifi_power_save_mode}

  # Fallback to AP if WiFi connection fails
  manual_ip:  # Optional for fixed IP after setup
    static_ip: ${manual_ip_static_ip}
    gateway: ${manual_ip_gateway}
    subnet: ${manual_ip_subnet}

  ap:
    ssid: ${ap_ssid}
    password: ${ap_password}

api:
  #encryption: 
   # key: ${api_key}
 # password: ${api_key} # Plain API: Encryption disabled for testing.

ota:
  - platform: esphome
    password: ${ota_password}

captive_portal:

mdns:
  disabled: false

web_server:
  port: 80
  include_internal: true

packages:
  - !include iaq-project/packages/bmp280_espnow_pressure_publish.yaml # espnow broadcast pressure sensor
  - !include iaq-project/packages/bmp280_espnow_weathertrend_publish.yaml # espnow broadcast calc'd weather trend
  - !include iaq-project/common/espnow.yaml # shared sensor broadcast
  - !include iaq-project/packages/aht20bmp280.yaml #AHT20-BMP280 t/h/pres
#  - !include iaq-project/packages/aht20.yaml # temp/hum sensor
  - !include iaq-project/packages/sgp30.yaml # eCO2, TVOC, 
#  - !include iaq-project/packages/MH-Z19.yaml #mh-z19 CO2 Sensor
#  - !include iaq-project/packages/SSD1306-64x48.yaml  # display2
#  - !include iaq-project/packages/SSD1306-128x64-local.yaml  # display1 local with bmp280 sensor
  - !include iaq-project/packages/SSD1306-128x64-local-w-countdown.yaml  # with countdown to sleep. display1/2, local (with bmp280 sensor) or remote    
  - !include iaq-project/packages/display-fonts.yaml  # arial
  - !include iaq-project/packages/max17048.yaml #max17048 Fuel Guage
  - !include iaq-project/packages/PMSX003.yaml #PMSX003, 7003
  - !include iaq-project/boards/Board-AITrip-ESP32-C3-FN4-Super-Mini.yaml #Board specific GPIO, etc.
  - !include iaq-project/common/base.yaml  # Hardware, logger, wifi, api, ota, etc.
  - !include iaq-project/common/sensors.yaml  # All sensors and text_sensors
  - !include iaq-project/common/sleep.yaml  # Deep sleep, globals, intervals
  - !include iaq-project/common/diagnostics.yaml # resets, reasons