sensor:
  - platform: aht10   # 0x38
    variant: AHT20
    id: aht20_sensor
    temperature:
      name: "${device_name} AHT20 Temp"
      id: fr_temp
      unit_of_measurement: "°F"
      accuracy_decimals: 1
      filters:
        - lambda: |-
            if (isnan(x)) return NAN;
            return x * (9.0/5.0) + 32.0;
    humidity:
      name: "${device_name} AHT20 Humidity"
      id: fr_humidity
      accuracy_decimals: 1
    update_interval: 30s
