# MH-Z19 sensor 
sensor:
  - platform: mhz19
    co2:
      name: "${device_name} MH-Z19 CO2 Sensor"
      id: co2

    temperature:
      name: "${device_name} MH-Z19 Temp"
    update_interval: 30s
    automatic_baseline_calibration: false  # Change to true for auto-cal in fresh air
    uart_id: mh
    id: mh_sensor

switch:
  - platform: template
    name: "CO2 Sensor Zero Calibration"
    turn_on_action:
      - mhz19.calibrate_zero: mh_sensor
      - switch.turn_off: co2_cal
    id: co2_cal
    entity_category: config

