sensor:
  - platform: tsl2561
      name: "Ambient Light"
      update_interval: 3s
      id: light_sens
      on_value:
        then:
          - light.control:
              id: led1
              brightness: !include includes/brightness.yaml
          - light.control:
              id: led2
              brightness: !include includes/brightness.yaml
          - light.control:
              id: led3
              brightness: !include includes/brightness.yaml
          - lambda: |-
              if (id(light_sens).state < 2 && !id(night_mode)) { id(display_on) = false; }
              else { id(display_on) = true; }

globals:
  - id: button_mode
    type: int
    initial_value: '1'
  - id: brightness_correction
    type: float
    restore_value: yes
    initial_value: '0.15'
  - id: version
    type: bool
    initial_value: 'false'
  - id: led_status
    type: bool
    initial_value: 'true'
    restore_value: yes
  - id: display_on
    type: bool
    initial_value: 'true'
  - id: led_status_display
    type: bool
    initial_value: 'false'
  - id: night_mode
    type: bool
    restore_value: yes
  - id: night_mode_display
    type: bool
  - id: pm_min
    type: float
    initial_value: '300.0'
  - id: pm_max
    type: float
    initial_value: '0.0'
  - id: co_min
    type: float
    initial_value: '5000.0'
  - id: co_max
    type: float
    initial_value: '0.0'
  - id: temp_min
    type: float
    initial_value: '50.0'
  - id: temp_max
    type: float
    initial_value: '0.0'
  - id: min_max_zero
    type: bool
    initial_value: 'false'